# Generated by Django 6.1.1 on 2026-10-01 23:58

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('oidc_provider', '0028_alter_client_id_alter_code_id_alter_responsetype_id_and_more'),
        ('smartauth_provider', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, verbose_name='Código del permiso')),
                ('description', models.TextField(verbose_name='Descripción del permiso')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oidc_provider.client', verbose_name='Aplicación Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oidc_provider.client', verbose_name='Aplicación Cliente')),
                ('permissions', models.ManyToManyField(blank=True, to='smartauth_manager.permission', verbose_name='Permisos de usuario')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Rol')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oidc_provider.client', verbose_name='Aplicación Cliente')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='Grupo')),
                ('permissions', models.ManyToManyField(blank=True, to='smartauth_manager.permission', verbose_name='Permisos de grupo')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfilePicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='auth/profile_pics/', verbose_name='Imagen de Perfil')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_picture', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ClaimCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Valor')),
                ('description', models.CharField(max_length=255, verbose_name='Nombre o Descripción')),
                ('parent_value', models.CharField(blank=True, max_length=255, verbose_name='Valor de Claim Padre')),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_values', to='smartauth_provider.claim', verbose_name='Claim')),
            ],
            options={
                'constraints': [models.UniqueConstraint(models.F('claim'), models.F('value'), models.F('parent_value'), name='unique_claim_catalog_Value')],
            },
        ),
        migrations.CreateModel(
            name='GroupClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='oidc_provider.client', verbose_name='Aplicación Cliente')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='auth.group', verbose_name='Grupo')),
            ],
            options={
                'constraints': [models.UniqueConstraint(models.F('group'), models.F('client'), name='unique_group_client')],
            },
        ),
        migrations.AddConstraint(
            model_name='permission',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), models.F('client'), name='unique_client_permission'),
        ),
    ]
